// Generated types — derived from JSON Schema via quicktype
export type {
	AddCookieParams,
	AlertTextResult,
	AttributeResult,
	BooleanResult,
	BrowserName,
	Capabilities,
	Cookie,
	CssValueResult,
	DeleteCookieParams,
	ElementIdParams,
	ExecuteScriptParams,
	FindElementParams,
	FindElementResult,
	FindElementsResult,
	GetAllCookiesResult,
	GetAttributeParams,
	GetCookieParams,
	GetCookieResult,
	GetCssValueParams,
	GetCurrentUrlResult,
	GetPageSourceResult,
	GetPropertyParams,
	GetTitleResult,
	Locator,
	LocatorStrategy,
	NavigateParams,
	NewSessionParams,
	NewSessionResult,
	PropertyResult,
	Rect,
	SameSite,
	ScreenshotResult,
	ScriptResult,
	SendAlertTextParams,
	SendKeysParams,
	SetWindowRectParams,
	TagNameResult,
	TakeScreenshotParams,
	TextResult,
} from "./generated/types.js";

// Functional driver interface
export {
	type SessionHandlers,
	type NavigationHandlers,
	type ElementHandlers,
	type ScriptHandlers,
	type CookieHandlers,
	type WindowHandlers,
	type ScreenshotHandlers,
	type AlertHandlers,
	type Driver,
	type DriverComponents,
	createDriver,
} from "./driver.js";

// Error types
export {
	DriverError,
	SessionNotCreatedError,
	NoSuchElementError,
	StaleElementReferenceError,
	ElementNotInteractableError,
	NoSuchAlertError,
	NoSuchWindowError,
	ScriptTimeoutError,
	TimeoutError,
	InvalidSelectorError,
	UnsupportedOperationError,
} from "./errors.js";
